### ISSUE TITLE
preferredForm translation and nameEntry attributes

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/eac1-to-eac2-conversion#5]
The transformation for preferredForm is a bit odd - looking at the Frankenstein file, the preferredForm string is being lost into a comment, but the nameEntry has "preferredForm=true".  The same goes for authorizedForm, although that may be less relevant since the authorized attribute just flags that an authorized form exists.

**Comment by fordmadox** [comment]
This is one area that will be detailed in the release notes, but for some of the background discussion on the mapping part, see https://github.com/SAA-SDT/eac-cpf-schema/issues/117#issuecomment-762153648 and below :)

**Comment by kerstarno** [comment]
@alexduryee To spare you reading through the rather lengthy decision process in #117  ;-) : the content of the elements `<authorizedForm>`, `<alternativeForm>`, and `<preferredForm>` is actually moved to a new `<conventionDeclaration>` element seeing that they are intended to capture the rule(s) according to which a name entry is an authorised, alternative, or preferred form. The `<nameEntry>` links to these via the `@conventionDeclarationReference`.

Hope that makes this part of the transformation clearer.

**Comment by fordmadox** [comment]
Closing this issue out, as discussed above.
