### ISSUE TITLE
transliteration and conventionDeclaration

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/eac1-to-eac2-conversion#6]
I could be interpreting conventionDeclaration incorrectly, but I'm not quite sure why transliteration attributes are being moved up to it.

**Comment by kerstarno** [comment]
@alexduryee This is because `@transliteration` is meant to "designat[e] the transliteration scheme", i.e. the rule (or convention) followed when transcribing from one writing system into the other.

**Comment by fordmadox** [comment]
Closing this issue out, as discussed above.
