### ISSUE TITLE
Values for @id in <conventionDeclaration> don't validate if in timezone east of GMT

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eac1-to-eac2-conversion#8]
This seems to relate to the conversion of `@transliteration` to `<conventionDeclaration>`. The conversion script adds a timespan to the value of `@id`, which works fine as long as the timezone is "-HH:mm", but will not validate if it's "+HH:mm" because of the + sign.

This also affects `@conventionDeclarationReference` pointing to one of the "faulty" ID-s.

It seems to be due to the "generate-id()" function for this part, which is picking up on the time settings of the hardware used.

```
<xsl:template match="eac:conventionDeclaration | eac:localTypeDeclaration | eac:rightsDeclaration">
  <xsl:element name="{local-name()}" namespace="{$eac-xmlns}">
    <xsl:apply-templates select="@* except @localType"/>
    <xsl:if test="not(@xml:id)">
      <xsl:attribute name="id" select="generate-id()"/>
    </xsl:if>
    <xsl:apply-templates select="eac:citation, eac:* except eac:citation | comment() | processing-instruction()"/>
  </xsl:element>
  <xsl:apply-templates select="@localType" mode="standalone-comment"/>
</xsl:template>
```

**Comment by fordmadox** [comment]
Ah, thanks!  Just issued a patch here, https://github.com/SAA-SDT/eac1-to-eac2-conversion/commit/322e096ba068fec62e8577ea4bd7880b35c0052e.  Hopefully that should cover it, but if not I could look at some extension for generating a UUID.

**Comment by kerstarno** [comment]
@fordmadox Thanks. I've just re-run the conversion with the patch and can confirm that it now goes through without any issues.

**Comment by fordmadox** [comment]
Closing, since the output is valid regardless of timezone.
